route:
  receiver: local-team-inbox
  group_wait: 1s
  group_interval: 5s
  repeat_interval: 1h
receivers:
  - name: local-team-inbox
    webhook_configs:
      - url: http://127.0.0.1:9194/alerts
        send_resolved: true
